### ISSUE TITLE
Low performance for mapArray

### ISSUE THREAD

**Issue by gpcaretti** [marviobezerra/KoAutoMap#1]
Updating an observable array even with few items generates an observable trigger for each items, this slow down the browsers.

I kindly suggest your an optimization of the following patch suggest here:
http://www.knockmeout.net/2012/04/knockoutjs-performance-gotcha.html

This code does exactly the same thing of the original code but it fires only one changing event at the end of the filling.

```javascript
ko.autoMap = {
	...
	mapArray: function (jsArray, observableArray) {
		var items = [];
		// observableArray.valueWillMutate(); - this might be invoked if you like
		for (var i = 0; jsArray && (i < jsArray.length) ; i++) {
			var item = new ko.observable();
			this.map(jsArray[i], item);
			items.push(item());
		}
		observableArray(items);
	},
	...
}

**Comment by marviobezerra** [comment]
I will fix this accepting your idea, thank you! Sorry for the delay (=

**Comment by gpcaretti** [comment]
Hi Mario,
I am happy you like my solution.

Anyway you did a typo in your code. You missed an 's':

mapArray: function (jsArray, observableArray) {

    observableArray([]);

    var items = [];
    for (var i = 0; i < jsArray.length; i++) {
        var item = new ko.observable();
        this.map(jsArray[i], item);
        items.push(item());
    }




*// error    observableArray(item);    // correct:*
*observableArray(items);* },



2015-11-03 18:35 GMT+01:00 Márvio André <notifications@github.com>:

**Comment by marviobezerra** [comment]
Sorry, my mistake! 
I fix it and one more time thank you!
